kind: Deployment
apiVersion: apps/v1

metadata:
  name: backend-deployment
  namespace: devboard
  labels:
    app: devboard-back

spec:
  replicas: 1
  selector:
    matchLabels:
      app: devboard-back

  template:
    metadata:
      name: backend-devboard 
      namespace: devboard
      labels:
        app: devboard-back

    spec:
      containers:
       - name:  backend-devboard 
         image: shashank971/devboard-backend:latest
         ports:
          - containerPort: 8080
