kind: Deployment
apiVersion: apps/v1

metadata:
  name: frontend-deployment
  namespace: devboard
  labels:
      app: devboard-front

spec:
  replicas: 3
  selector:
    matchLabels:
      app: devboard-front

  template:
    metadata:
      name: devboard-frontend
      namespace: devboard
      labels:
        app: devboard-front

    spec:
      containers:
        - name: devboard-frontend    
          image: shashank971/devboard-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "250Mi"
            limits:
              cpu: "200m"
              memory: " 500Mi"      
