kind: PersistentVolume
apiVersion: v1

metadata:
  name: pv-devboard
  labels:
    app: devboard-pv

spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data    