kind: PersistentVolumeClaim
apiVersion: v1

metadata:
  name: pvc-devboard
  namespace: #devboard

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
   matchLabels:
     app:  devboard-pv

