kind: ServiceAccount
apiVersion: v1
metadata:
  name: devboard-intern
  namespace: devboard

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devboard-admin
  namespace: devboard


#--------------commands for testing-----------------------
# kubectl auth can-i delete deployments -n devboard --as=system:serviceaccount:devboard:devboard-admin
# kubectl auth can-i patch pods -n devboard --as=system:serviceaccount:devboard:devboard-admin
# kubectl auth can-i create deployment -n devboard
# kubectl auth can-i watch deployments -n devboard --as=devboard-intern
# kubectl auth can-i delete  deployments -n devboard --as=devboard-intern

