name: CODE QUALITY  

on:
  workflow-call:

jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
     - name: code checkout
       uses: actions/checkout@v7

     - name: set up node
       uses: actions/setup-node@v7
       with:
        node-version: '26'
        cache: npm
        cache-dependency-path: frontend/package-lock.json

     - name: installing npm packages
       run: npm ci --legacy-peer-deps
       working-directory: frontend

     - name: linting for node
       run: npm run lint
       working-directory: frontend

     - name: set up go 
       uses: actions/setup-go@v7
       with:
        go-version: '1.22'
        go-version-file: go.mod
        cache-dependency-path:  go.sum     

     - name: run go formatter
       run: go fmt 
       working-directory: backend

     - name: run go vet
       run: go vet
       working-directory: backend     