name: DEPENDENCY CHECK 

on: 
  workflow_call:

jobs:
  dependency_check:
   runs-on: ubuntu-latest
 # ---------------- FRONTEND ----------------  
   steps:
    - name: code checkout
      uses: actions/checkout@v7

    - name: setup node
      uses: actions/setup-node@v7
      with:
        node-version: '26'
        cache: npm
        cache-dependency-path: frontend/package-lock.json 

    - name: install dependency
      run: npm ci --legacy-peer-deps
      working-directory: frontend
    
    - name:  Dependency Vulnerability Scan
      run: npm audit
      working-directory: frontend
# ---------------- BACKEND ----------------
    - name: setup go
      uses: actions/setup-go@v7
      with:
        go-version: '1.22'
        go-version-file: backend/go.mod
        cache-dependency-path: backend/go.sum

    - name: Download Dependencies
      run: go mod download
      working-directory: backend

    - name: Run Govulncheck
      run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...
      working-directory: backend


#-------------for fixing dependency issues----------------------
#cd frontend
#npm install -D @vitejs/plugin-react@latest
#npm audit fix
#npm audit      
#npm install react-router-dom@7.18.3
#npm audit