name: DOCKER SCAN

on:
  workflow_call:

jobs:
  docker_scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
       folders: [frontend,backend]  
    steps:
     - name: code checkout
       uses: actions/checkout@v7

     - name: hadolint
       uses: hadolint/hadolint-action@v3.1.0
       with:
        dockerfile: ${{ matrix.folders}}/Dockerfile     

        